# options[country][governorate][city]
location_options = {
    "Egypt": {
        "": [],
        "Alexandria": [
            "Damietta",
            "Elalyoubia",
            "Elbehira",
            "Eldakahlia",
            "Elfayoum",
            "Elgharbia",
            "Elgiza",
            "Elismailia",
            "Elkalubia",
            "Elminofia",
            "Elminia",
            "Elsharkia",
            "Elsuez",
            "Elwadi Elgidid",
            "Kafr Elsheikh",
            "Luxor",
            "Matoruh",
            "North Sinai",
            "Port Said",
            "Qena",
            "Red Sea",
            "Sohag",
            "South Sinai",
        ],
        "Assuit": [],
        "Aswan": [],
        "Beni Suef": [],
        "Cairo": [],
        "Damietta": [],
        "Elalyoubia": [],
        "Elbehira": [],
        "Eldakahlia": [],
        "Elfayoum": [],
        "Elgharbia": [],
        "Elgiza": [],
        "Elismailia": [],
        "Elkalubia": [],
        "Elminofia": [],
        "Elminia": [],
        "Elsharkia": [],
        "Elsuez": [],
        "Elwadi Elgidid": [],
        "Kafr Elsheikh": [],
        "Luxor": [],
        "Matoruh": [],
        "North Sinai": [],
        "Port Said": [],
        "Qena": [],
        "Red Sea": [],
        "Sohag": [],
        "South Sinai": [],
    },
}
